[package]
name = "tw-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "路由规则引擎与策略组"

[dependencies]
serde = { workspace = true }
tw-redact = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_yaml_ng = { workspace = true }
