[package]
name = "tw-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
description = "Routing rule engine and policy groups"

[dependencies]
serde = { workspace = true }
tw-dialect = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tw-types = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_yaml_ng = { workspace = true }
