//! 把契约导出成一个 TypeScript 文件（`ts` feature）。
//!
//! **从端点表出发，不从一张手写的类型清单出发。**每个端点的请求和响应类型
//! 连同它们引用到的一切都会导出；一个不在任何端点上出现的类型不在线上，
//! 也就不该出现在前端。手写清单会漏，而漏掉的表现是前端又开始手写那个类型。
//!
//! 几个取舍：
//! - **64 位整数导出成 `number`，不是 ts-rs 默认的 `bigint`。**线上是 JSON，
//!   `JSON.parse` 给出来的就是 `number`；类型写成 `bigint` 只会让类型和值对不上。
//!   毫秒时间戳、字节数、token 数都远小于 2^53。
//! - `Option` + `skip_serializing_if` 的字段是 `name?: T`，没带的是 `name: T | null`，
//!   和 serde 实际发出的一致。
//! - 文档注释原样带过去，成了 JSDoc。

use std::any::TypeId;
use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};

use ts_rs::{Config, TS, TypeVisitor};

use crate::endpoint::Endpoint;

/// 导出的文件名。
pub const FILE: &str = "tw-api.ts";

/// 端点表对每个端点做的事。由 `endpoints!` 生成的 `visit_types` 调用。
pub(crate) trait Visit {
    fn endpoint<E: Endpoint>(&mut self)
    where
        E::Req: TS + 'static,
        E::Res: TS + 'static;
}

struct Collect {
    cfg: Config,
    seen: HashSet<TypeId>,
    /// 名字 → 声明。按名字排，输出稳定
    decls: BTreeMap<String, (TypeId, String)>,
    endpoints: Vec<(&'static str, String, String)>,
}

impl TypeVisitor for Collect {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        // 基本类型、Vec、Option 这些没有自己的声明
        if T::output_path().is_none() || !self.seen.insert(TypeId::of::<T>()) {
            return;
        }
        let name = T::ident(&self.cfg);
        let mut decl = T::docs().unwrap_or_default();
        decl.push_str("export ");
        decl.push_str(&T::decl(&self.cfg));
        if let Some((other, _)) = self.decls.insert(name.clone(), (TypeId::of::<T>(), decl)) {
            // 两个 Rust 类型导出成同一个名字，前端只能看到其中一个
            assert_eq!(
                other,
                TypeId::of::<T>(),
                "two wire types are both named `{name}` in TypeScript"
            );
        }
        T::visit_dependencies(self);
    }
}

impl Collect {
    /// 一个出现在端点上的类型：它自己，加上它的类型参数（`Vec<X>` 的 `X`）。
    fn root<T: TS + 'static + ?Sized>(&mut self) {
        self.visit::<T>();
        T::visit_generics(self);
    }
}

impl Visit for Collect {
    fn endpoint<E: Endpoint>(&mut self)
    where
        E::Req: TS + 'static,
        E::Res: TS + 'static,
    {
        self.root::<E::Req>();
        self.root::<E::Res>();
        let req = <E::Req as TS>::name(&self.cfg);
        let res = <E::Res as TS>::name(&self.cfg);
        self.endpoints.push((E::NAME, req, res));
    }
}

/// 整个契约，一个 TypeScript 模块。
pub fn typescript() -> String {
    let mut c = Collect {
        cfg: Config::new().with_large_int("number"),
        seen: HashSet::new(),
        decls: BTreeMap::new(),
        endpoints: Vec::new(),
    };
    crate::ep::visit_types(&mut c);
    c.root::<crate::endpoint::ErrorBody>();

    let mut out =
        String::from("// Generated by tw-api (`tw_api::ts::export_all`). Do not edit by hand.\n\n");
    out.push_str(&format!(
        "export const CONTROL_API_VERSION = {};\n\n",
        crate::CONTROL_API_VERSION
    ));
    for (_, decl) in c.decls.values() {
        out.push_str(decl);
        out.push_str("\n\n");
    }
    out.push_str(
        "// The body of every non-2xx control-plane response.\nexport type ErrorBody = Msg;\n\n",
    );

    out.push_str("export const ENDPOINTS = {\n");
    for e in crate::ep::ALL {
        let params: Vec<String> = e.params.iter().map(|p| format!("\"{p}\"")).collect();
        out.push_str(&format!(
            "  {}: {{ method: \"{}\", path: \"{}\", params: [{}], format: \"{}\" }},\n",
            e.name,
            e.method.as_str(),
            e.path,
            params.join(", "),
            e.format.as_str()
        ));
    }
    out.push_str("} as const;\n\n");

    out.push_str(
        "// Request and response types per endpoint. `req` travels as the query string for GET\n// and DELETE, as the JSON body otherwise; `null` means none.\nexport type Endpoints = {\n",
    );
    for (name, req, res) in &c.endpoints {
        out.push_str(&format!("  {name}: {{ req: {req}; res: {res} }};\n"));
    }
    out.push_str("};\n\nexport type EndpointName = keyof Endpoints;\n");
    out
}

/// 把 [`typescript`] 写到 `dir/tw-api.ts`，返回写到的路径。目录不存在就建。
pub fn export_all(dir: &Path) -> std::io::Result<PathBuf> {
    std::fs::create_dir_all(dir)?;
    let path = dir.join(FILE);
    std::fs::write(&path, typescript())?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn decl_of(ts: &str, name: &str) -> String {
        let start = ts
            .find(&format!("export type {name} = "))
            .unwrap_or_else(|| panic!("`{name}` was not exported"));
        let rest = &ts[start..];
        rest[..rest.find(";\n").unwrap()].to_string()
    }

    /// 线上是 JSON，64 位整数在 JS 里就是 `number`。
    #[test]
    fn large_integers_are_numbers_not_bigints() {
        let ts = typescript();
        assert!(!ts.contains("bigint"), "a bigint slipped through");
        let usage = decl_of(&ts, "UsageView");
        assert!(usage.contains("input: number"), "{usage}");
    }

    /// `Option` + `skip_serializing_if` 是可以不出现的字段；没带的是可以为 null 的字段。
    #[test]
    fn optional_fields_follow_what_serde_actually_sends() {
        let ts = typescript();
        let status = decl_of(&ts, "Status");
        assert!(status.contains("listen_error?: Msg"), "{status}");
        assert!(status.contains("gateway_addr: string | null"), "{status}");
        let usage = decl_of(&ts, "UsageView");
        assert!(usage.contains("cache_1h?: boolean"), "{usage}");
    }

    /// 带 tag 的枚举导出成可辨识联合，前端按 `kind` 分派。
    #[test]
    fn tagged_enums_become_discriminated_unions() {
        let ts = typescript();
        let event = decl_of(&ts, "Event");
        assert!(event.contains("\"kind\": \"request_started\""), "{event}");
        let patch = decl_of(&ts, "PatchValue");
        assert!(!patch.contains("\"kind\""), "untagged: {patch}");
    }

    #[test]
    fn maps_and_messages_come_through() {
        let ts = typescript();
        let msg = decl_of(&ts, "Msg");
        assert!(msg.contains("args?: { [key in string]: string }"), "{msg}");
        let sheet = decl_of(&ts, "PriceSheetInput");
        assert!(
            sheet.contains("{ [key in string]: PriceFields }"),
            "{sheet}"
        );
    }

    #[test]
    fn every_endpoint_is_in_the_table() {
        let ts = typescript();
        for e in crate::ep::ALL {
            assert!(
                ts.contains(&format!("  {}: {{ method: ", e.name)),
                "{}",
                e.name
            );
            assert!(
                ts.contains(&format!("  {}: {{ req: ", e.name)),
                "{}",
                e.name
            );
        }
        assert!(ts.contains("  Status: { req: null; res: Status };"));
        assert!(ts.contains("  L1: { req: L1Request; res: Array<L1Result> };"));
        assert!(ts.contains(
            "  Events: { method: \"GET\", path: \"/events\", params: [], format: \"events\" },"
        ));
    }

    #[test]
    fn it_writes_one_file() {
        let dir = std::env::temp_dir().join(format!("tw-api-ts-{}", std::process::id()));
        let path = export_all(&dir).unwrap();
        assert_eq!(path, dir.join(FILE));
        assert_eq!(std::fs::read_to_string(&path).unwrap(), typescript());
        std::fs::remove_dir_all(&dir).unwrap();
    }
}
