//! 把契约导出成一个 TypeScript 文件（`ts` feature）。
//!
//! **从端点表出发，不从一张手写的类型清单出发。**每个端点的请求和响应类型
//! 连同它们引用到的一切都会导出；一个不在任何端点上出现的类型不在线上，
//! 也就不该出现在前端。手写清单会漏，而漏掉的表现是前端又开始手写那个类型。
//!
//! 几个取舍：
//! - **64 位整数导出成 `number`，不是 ts-rs 默认的 `bigint`。**线上是 JSON，
//!   `JSON.parse` 给出来的就是 `number`；类型写成 `bigint` 只会让类型和值对不上。
//!   毫秒时间戳、字节数、token 数都远小于 2^53。
//! - `Option` + `skip_serializing_if` 的字段是 `name?: T`，没带的是 `name: T | null`，
//!   和 serde 实际发出的一致。
//! - 文档注释原样带过去，成了 JSDoc。

use std::any::TypeId;
use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};

use ts_rs::{Config, TS, TypeVisitor};

use crate::endpoint::Endpoint;

/// 导出的文件名。
pub const FILE: &str = "tw-api.ts";

/// 端点表对每个端点做的事。由 `endpoints!` 生成的 `visit_types` 调用。
pub(crate) trait Visit {
    fn endpoint<E: Endpoint>(&mut self)
    where
        E::Req: TS + 'static,
        E::Res: TS + 'static;
}

struct Collect {
    cfg: Config,
    seen: HashSet<TypeId>,
    /// 名字 → 声明。按名字排，输出稳定
    decls: BTreeMap<String, (TypeId, String)>,
    endpoints: Vec<(&'static str, String, String)>,
}

impl TypeVisitor for Collect {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        // 基本类型、Vec、Option 这些没有自己的声明
        if T::output_path().is_none() || !self.seen.insert(TypeId::of::<T>()) {
            return;
        }
        let name = T::ident(&self.cfg);
        let mut decl = T::docs().unwrap_or_default();
        decl.push_str("export ");
        decl.push_str(&T::decl(&self.cfg));
        if let Some((other, _)) = self.decls.insert(name.clone(), (TypeId::of::<T>(), decl)) {
            // 两个 Rust 类型导出成同一个名字，前端只能看到其中一个
            assert_eq!(
                other,
                TypeId::of::<T>(),
                "two wire types are both named `{name}` in TypeScript"
            );
        }
        T::visit_dependencies(self);
    }
}

impl Collect {
    /// 一个出现在端点上的类型：它自己，加上它的类型参数（`Vec<X>` 的 `X`）。
    fn root<T: TS + 'static + ?Sized>(&mut self) {
        self.visit::<T>();
        T::visit_generics(self);
    }
}

impl Visit for Collect {
    fn endpoint<E: Endpoint>(&mut self)
    where
        E::Req: TS + 'static,
        E::Res: TS + 'static,
    {
        self.root::<E::Req>();
        self.root::<E::Res>();
        let req = <E::Req as TS>::name(&self.cfg);
        let res = <E::Res as TS>::name(&self.cfg);
        self.endpoints.push((E::NAME, req, res));
    }
}

/// 整个契约，一个 TypeScript 模块。
pub fn typescript() -> String {
    let mut c = Collect {
        cfg: Config::new().with_large_int("number"),
        seen: HashSet::new(),
        decls: BTreeMap::new(),
        endpoints: Vec::new(),
    };
    crate::ep::visit_types(&mut c);
    c.root::<crate::endpoint::ErrorBody>();

    let mut out =
        String::from("// Generated by tw-api (`tw_api::ts::export_all`). Do not edit by hand.\n\n");
    out.push_str(&format!(
        "export const CONTROL_API_VERSION = {};\n\n",
        crate::CONTROL_API_VERSION
    ));
    for (_, decl) in c.decls.values() {
        out.push_str(decl);
        out.push_str("\n\n");
    }
    out.push_str(
        "// The body of every non-2xx control-plane response.\nexport type ErrorBody = Msg;\n\n",
    );

    out.push_str("export const ENDPOINTS = {\n");
    for e in crate::ep::ALL {
        let params: Vec<String> = e.params.iter().map(|p| format!("\"{p}\"")).collect();
        out.push_str(&format!(
            "  {}: {{ method: \"{}\", path: \"{}\", params: [{}], format: \"{}\" }},\n",
            e.name,
            e.method.as_str(),
            e.path,
            params.join(", "),
            e.format.as_str()
        ));
    }
    out.push_str("} as const;\n\n");

    out.push_str(
        "// Request and response types per endpoint. `req` travels as the query string for GET\n// and DELETE, as the JSON body otherwise; `null` means none.\nexport type Endpoints = {\n",
    );
    for (name, req, res) in &c.endpoints {
        out.push_str(&format!("  {name}: {{ req: {req}; res: {res} }};\n"));
    }
    out.push_str("};\n\nexport type EndpointName = keyof Endpoints;\n");
    out
}

/// 把 [`typescript`] 写到 `dir/tw-api.ts`，返回写到的路径。目录不存在就建。
pub fn export_all(dir: &Path) -> std::io::Result<PathBuf> {
    std::fs::create_dir_all(dir)?;
    let path = dir.join(FILE);
    std::fs::write(&path, typescript())?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn decl_of(ts: &str, name: &str) -> String {
        let start = ts
            .find(&format!("export type {name} = "))
            .unwrap_or_else(|| panic!("`{name}` was not exported"));
        let rest = &ts[start..];
        rest[..rest.find(";\n").unwrap()].to_string()
    }

    /// 线上是 JSON，64 位整数在 JS 里就是 `number`。
    #[test]
    fn large_integers_are_numbers_not_bigints() {
        let ts = typescript();
        assert!(!ts.contains("bigint"), "a bigint slipped through");
        let usage = decl_of(&ts, "UsageView");
        assert!(usage.contains("input: number"), "{usage}");
    }

    /// `Option` + `skip_serializing_if` 是可以不出现的字段；没带的是可以为 null 的字段。
    #[test]
    fn optional_fields_follow_what_serde_actually_sends() {
        let ts = typescript();
        let status = decl_of(&ts, "Status");
        assert!(status.contains("listen_error?: Msg"), "{status}");
        assert!(status.contains("gateway_addr: string | null"), "{status}");
        let usage = decl_of(&ts, "UsageView");
        assert!(usage.contains("cache_1h?: boolean"), "{usage}");
    }

    /// 带 tag 的枚举导出成可辨识联合，前端按 `kind` 分派。
    #[test]
    fn tagged_enums_become_discriminated_unions() {
        let ts = typescript();
        let event = decl_of(&ts, "Event");
        assert!(event.contains("\"kind\": \"request_started\""), "{event}");
        let patch = decl_of(&ts, "PatchValue");
        assert!(!patch.contains("\"kind\""), "untagged: {patch}");
    }

    #[test]
    fn maps_and_messages_come_through() {
        let ts = typescript();
        let msg = decl_of(&ts, "Msg");
        assert!(msg.contains("args?: { [key in string]: string }"), "{msg}");
        let sheet = decl_of(&ts, "PriceSheetInput");
        assert!(
            sheet.contains("{ [key in string]: PriceFields }"),
            "{sheet}"
        );
    }

    /// 集合不归我们定的字段：认得的词是字面量，其余照样是字符串。
    #[test]
    fn an_open_set_is_its_known_words_or_any_string() {
        let ts = typescript();
        assert_eq!(
            decl_of(&ts, "ChatgptPlan"),
            "export type ChatgptPlan = KnownChatgptPlan | string"
        );
        let known = decl_of(&ts, "KnownChatgptPlan");
        assert!(known.contains("\"prolite\""), "{known}");
        let oauth = decl_of(&ts, "OAuthView");
        assert!(oauth.contains("account?: AccountView"), "{oauth}");
        // 登录结果说的账号和上游视图是同一块
        let login = decl_of(&ts, "ChatgptLoginStatus");
        assert!(login.contains("account?: AccountView"), "{login}");
        assert!(!login.contains("plan"), "{login}");
    }

    /// 会话里的一轮说得出上游回了什么：状态码和失败的原因都是必有的字段，没有时是 null
    #[test]
    fn a_turn_says_what_the_upstream_answered() {
        let ts = typescript();
        let turn = decl_of(&ts, "TurnView");
        for field in [
            "status: number | null",
            "error: Msg | null",
            "cancelled: boolean",
        ] {
            assert!(turn.contains(field), "{field}: {turn}");
        }
    }

    /// 命中数带着记录从哪一刻起是全的：必有的字段，没有记录时是 null，不是省掉。
    #[test]
    fn route_stats_say_where_their_history_starts() {
        let ts = typescript();
        let stats = decl_of(&ts, "RouteStats");
        assert!(stats.contains("covered_since_ms: number | null"), "{stats}");
        assert!(stats.contains("routes: Array<RouteHits>"), "{stats}");
        assert!(ts.contains("  RouteStats: { req: Window; res: RouteStats };"));
    }

    /// 搜索的一页：接着找的位置和正文留到哪一刻是必有的字段，没有时是 null；请求里
    /// 不给的条件可以整个省掉
    #[test]
    fn a_search_page_says_where_to_go_on_from() {
        let ts = typescript();
        let page = decl_of(&ts, "HistorySearchPage");
        assert!(page.contains("rows: Array<HistoryRow>"), "{page}");
        assert!(page.contains("hits: Array<ContentHit>"), "{page}");
        assert!(page.contains("next: HistoryCursor | null"), "{page}");
        assert!(page.contains("bodies_since_ms: number | null"), "{page}");
        assert!(page.contains("stopped: SearchStop"), "{page}");
        let q = decl_of(&ts, "HistorySearchQuery");
        for field in [
            "q?: string",
            "failed?: boolean",
            "error_codes?: Array<string>",
            "before?: HistoryCursor",
            "limit?: number",
        ] {
            assert!(q.contains(field), "{field}: {q}");
        }
        assert_eq!(
            decl_of(&ts, "SearchStop"),
            "export type SearchStop = \"full\" | \"budget\" | \"end\""
        );
        assert!(
            ts.contains("  HistorySearch: { req: HistorySearchQuery; res: HistorySearchPage };")
        );
        assert!(ts.contains(
            "  HistorySearch: { method: \"POST\", path: \"/history/search\", params: [], format: \"json\" },"
        ));
    }

    /// 上游体检：没有样本的是 null（必有的字段，不是省掉），比值是普通的数
    #[test]
    fn the_upstream_checkup_says_what_it_has_no_samples_for() {
        let ts = typescript();
        assert!(ts.contains("  UpstreamHealth: { req: Window; res: UpstreamHealth };"));
        let health = decl_of(&ts, "UpstreamHealth");
        assert!(
            health.contains("covered_since_ms: number | null"),
            "{health}"
        );
        assert!(
            health.contains("upstreams: Array<UpstreamCheckup>"),
            "{health}"
        );
        let checkup = decl_of(&ts, "UpstreamCheckup");
        assert!(checkup.contains("ttft_ms: MedianView | null"), "{checkup}");
        let input = decl_of(&ts, "InputVsEstimate");
        assert!(input.contains("all: RatioView | null"), "{input}");
        let model = decl_of(&ts, "InputForModel");
        assert!(model.contains("others: RatioView | null"), "{model}");
        assert!(decl_of(&ts, "RatioView").contains("median: number"));
        // 事件上的两样是可以不出现的字段
        let event = decl_of(&ts, "Event");
        assert!(event.contains("input_estimate?: number"), "{event}");
        assert!(event.contains("answered_model?: string"), "{event}");
    }

    /// 对话记录：请求号是字符串；可以为空的是 null（必有的字段，不是省掉）；块是按 `kind`
    /// 分的联合，角色和缺口是字面量
    #[test]
    fn a_transcript_is_turns_of_messages_and_parts() {
        let ts = typescript();
        assert!(ts.contains("  SessionTranscript: { req: null; res: Transcript };"));
        assert!(ts.contains(
            "  SessionTranscript: { method: \"GET\", path: \"/sessions/{id}/transcript\", params: [\"id\"], format: \"json\" },"
        ));
        let transcript = decl_of(&ts, "Transcript");
        for field in [
            "session: string",
            "system: string | null",
            "turns: Array<TranscriptTurn>",
        ] {
            assert!(transcript.contains(field), "{field}: {transcript}");
        }
        let turn = decl_of(&ts, "TranscriptTurn");
        for field in [
            "id: string",
            "restart: boolean",
            "system_changed: string | null",
            "input: Array<TranscriptMessage>",
            "output: Array<TranscriptPart>",
            "gaps: Array<TranscriptGap>",
        ] {
            assert!(turn.contains(field), "{field}: {turn}");
        }
        assert_eq!(
            decl_of(&ts, "TranscriptMessage"),
            "export type TranscriptMessage = { role: TranscriptRole, parts: Array<TranscriptPart>, }"
        );
        assert_eq!(
            decl_of(&ts, "TranscriptPart"),
            "export type TranscriptPart = { \"kind\": \"text\", text: string, } \
             | { \"kind\": \"thinking\", text: string, } \
             | { \"kind\": \"tool_call\", id: string, name: string, input: string, } \
             | { \"kind\": \"tool_result\", call_id: string, text: string, is_error: boolean, } \
             | { \"kind\": \"image\", media_type: string | null, bytes: number | null, } \
             | { \"kind\": \"other\", label: string, }"
        );
        assert_eq!(
            decl_of(&ts, "TranscriptRole"),
            "export type TranscriptRole = \"user\" | \"assistant\" | \"tool\" | \"system\""
        );
        assert_eq!(
            decl_of(&ts, "TranscriptGap"),
            "export type TranscriptGap = \"request_missing\" | \"request_truncated\" \
             | \"response_missing\" | \"response_truncated\" | \"response_unreadable\""
        );
    }

    #[test]
    fn every_endpoint_is_in_the_table() {
        let ts = typescript();
        for e in crate::ep::ALL {
            assert!(
                ts.contains(&format!("  {}: {{ method: ", e.name)),
                "{}",
                e.name
            );
            assert!(
                ts.contains(&format!("  {}: {{ req: ", e.name)),
                "{}",
                e.name
            );
        }
        assert!(ts.contains("  Status: { req: null; res: Status };"));
        assert!(ts.contains("  L1: { req: L1Request; res: Array<L1Result> };"));
        assert!(ts.contains(
            "  Events: { method: \"GET\", path: \"/events\", params: [], format: \"events\" },"
        ));
    }

    #[test]
    fn it_writes_one_file() {
        let dir = std::env::temp_dir().join(format!("tw-api-ts-{}", std::process::id()));
        let path = export_all(&dir).unwrap();
        assert_eq!(path, dir.join(FILE));
        assert_eq!(std::fs::read_to_string(&path).unwrap(), typescript());
        std::fs::remove_dir_all(&dir).unwrap();
    }
}
